### ISSUE TITLE
can't see the pre-process nodes :( 

### ISSUE THREAD

**Issue by drorlazar** [Fannovel16/comfy_controlnet_preprocessors#4]
after installing everything (manually and more) i'm running the install.py and it seems to be successful, but when running comfyUI i can't see the pre-process nodes, I can see the Checkpoint custom nodes, but not the pre-process nodes, any help?

**Comment by paulo-coronado** [comment]
@Fannovel16  After running python `install.py`, I was getting this error:
```
[AssertionError: Torch not compiled with CUDA enabled in PyTorch](https://stackoverflow.com/questions/72581669/assertionerror-torch-not-compiled-with-cuda-enabled-in-pytorch)
```

To fix the issue, I ran:
```
pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113
```

However, when running ComfyUI, I got the following error:
```
ModuleNotFoundError: No module named 'cv2'
```

Even after running `install.py`, or trying to install via `pip install opencv-python`.

Just for letting me know, what is the name of the preprocess node?

**Comment by Fannovel16** [comment]
@drorlazar @paulo-coronado I updated the repo. Reclone this repo and check if the issue is still there.

**Comment by paulo-coronado** [comment]
Testing right, now! I am installing it normally via:
```
cd ComfyUI/custom_nodes
git clone https://github.com/Fannovel16/comfy_controlnet_preprocessors
cd comfy_controlnet_preprocessors
python install.py
```

**Comment by paulo-coronado** [comment]
I am testing the nodes right now!

**Comment by Fannovel16** [comment]
> To fix that, I ran:
> 
> ```
> ..\..\..\python_embeded\python.exe -m pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu117 --no-warn-script-location
> ```
> 
> And it worked! 🎉🎉🎉

You just need to run 
```
..\..\..\python_embeded\python.exe install.py
```
Since I included that command directly to install.py

**Comment by drorlazar** [comment]
> @drorlazar @paulo-coronado I updated the repo. Reclone this repo and check if the issue is still there.
Working!!! 
thanks!!
